export { default as Nextjs2 } from "./Nextjs2"
export { default as Redux } from "./Redux"
export { default as Typescript } from "./Typescript"
export { default as Angular } from "./Angular"
export { default as Express } from "./Express"
